version: "3.7"
services:
  webblog:
    container_name: vueblog-web-test
    image: vueblog-web:latest
    restart: unless-stopped
    build: .
    networks:
      vueblog:
        ipv4_address: 172.22.0.4
    ports:
      - 8080:8080/tcp

networks:
  vueblog:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"
